spring:
  application:
    name: rsocket-spring
  datasource:
    url: ${DATA_SOURCE_URL:mongodb://localhost:27017/market}

  rsocket:
    server:
      port: 3000

server:
  port: 8189
  error:
    include-message: always
  servlet:
    context-path: "/api"
